#!/usr/bin/env node
// Golden vectors for the GDScript port: the JS core (math 'det') computes them, sim/core/tools/parity.gd must
// reproduce every one bit for bit. Regenerate after an intended change to the core or to a .gd file's literals:
//   node sim/core/tools/golden.js            writes sim/core/test/golden-gd.json
//   node sim/core/tools/golden.js --check    exits 1 if the file is stale (run by npm test)
// Every vector is defined by a recipe that parity.gd repeats exactly: the same inputs, generated by the same float
// arithmetic, hashed with the same Hasher.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Hasher, collect, hashValues, portSrc, stateHash } from '../hash.js';
import { createRng, next } from '../rng.js';
import { wrap, sdx } from '../wrap.js';
import { DT } from '../constants.js';
import * as D from '../detmath.js';
import { createSim, newMatch, step, toggleAI } from '../sim.js';
import { createCamera, camStep } from '../view/camera.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const SIM = path.resolve(here, '..', '..');
export const GOLDEN = path.join(SIM, 'core', 'test', 'golden-gd.json');
const f64 = new Float64Array(1), u32 = new Uint32Array(f64.buffer);
export const bits = x => { f64[0] = x; return u32[1].toString(16).padStart(8, '0') + u32[0].toString(16).padStart(8, '0'); };

// A value list as tagged strings, for first-difference diagnostics on the GDScript side.
const tag = v => (typeof v === 'number' ? 'n:' + bits(v) : typeof v === 'string' ? 's:' + v : typeof v === 'boolean' ? 'b:' + (v ? 1 : 0) : 'z');

// Float literals in the .gd sources (integers are exact in any parser), with the bits a correct parser gives them.
function gdLiterals() {
  const out = new Map();
  const walk = dir => {
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      const p = path.join(dir, e.name);
      if (e.isDirectory()) walk(p);
      else if (e.name.endsWith('.gd')) {
        const src = fs.readFileSync(p, 'utf8').replace(/"[^"\n]*"/g, '""').replace(/#.*$/gm, '');
        for (const m of src.matchAll(/(?<![\w.])(\d+\.\d+(?:e[+-]?\d+)?|\d+e[+-]?\d+)(?![\w.])/g)) out.set(m[1], bits(Number(m[1])));
      }
    }
  };
  walk(SIM);
  return [...out].sort((a, b) => (a[0] < b[0] ? -1 : 1)).map(([lit, hex]) => ({ lit, hex }));
}

// Match setups ("arms"): the same as QA's (prototype/tools/match-runner.js), copied here so the golden contract does not
// move when QA's tools do. parity.gd has the GDScript copy.
const CHAR_KEYS = ['name', 'title', 'role', 'col', 'aura', 'hair', 'care', 'dmgMul', 'spd', 'maxhp', 'sigName'];
const pick = f => Object.fromEntries(CHAR_KEYS.map(k => [k, f[k]]));
const put = (f, c) => { Object.assign(f, c); f.hp = f.maxhp; };
const flip = fs => { fs[0].x = 2900; fs[1].x = 2150; fs[0].face = -1; fs[1].face = 1; };
export const ARMS = {
  'default': () => {},
  'swap': fs => { const a = pick(fs[0]), b = pick(fs[1]); put(fs[0], b); put(fs[1], a); },
  'mirror-villain': fs => { const v = pick(fs[1]); put(fs[0], { ...v, name: v.name + '-A' }); put(fs[1], { ...v, name: v.name + '-B' }); },
  'mirror-hero': fs => { const k = pick(fs[0]); put(fs[0], { ...k, name: k.name + '-A' }); put(fs[1], { ...k, name: k.name + '-B' }); },
};
for (const a of ['default', 'swap', 'mirror-villain', 'mirror-hero']) ARMS[a + '-flip'] = fs => { ARMS[a](fs); flip(fs); };
export const MATCHES = [...Array.from({ length: 10 }, (_, i) => ['default', i + 1]), ['swap', 1], ['mirror-villain', 1], ['mirror-hero', 1],
  ['default-flip', 2], ['swap-flip', 2], ['mirror-villain-flip', 2], ['mirror-hero-flip', 2]];
export const CHECK_EVERY = 120;

const camHash = cam => { const h = new Hasher(); h.num(cam.x); h.num(cam.y); h.num(cam.z); return h.hex(); };
const full = (S, cam) => { const s = stateHash(S); return s.gameplay + ':' + s.presentation + ':' + camHash(cam); };
const INTENT = ['mx', 'my', 'dash', 'charge', 'light', 'heavy', 'sig', 'stance'];

// One golden run. Every tick folds a light digest (time, rng, fighters' core numbers and state, the feed lines); every
// CHECK_EVERY ticks and at the end the full state (both lanes and the camera) is recorded. With a replay, the run
// applies its AI toggles and intents and lasts exactly replay.ticks; without, it runs to KO + 3 s or 18000 ticks.
export function goldenRun(arm, seed, replay = null) {
  const S = createSim({ math: 'det' }), cam = createCamera();
  newMatch(S, seed, replay ? replay.ai : undefined);
  ARMS[arm](S.fighters);
  const h = new Hasher(), checkpoints = [full(S, cam)], cur = [null, null];
  let steps = 0, ii = 0, ti = 0;
  const more = () => (replay ? steps < replay.ticks : steps < 18000 && !(S.game.ko && S.game.koT > 3));
  while (more()) {
    if (replay) {
      while (ti < replay.toggles.length && replay.toggles[ti][0] === steps) toggleAI(S, replay.toggles[ti++][1]);
      while (ii < replay.inputs.length && replay.inputs[ii][0] === steps) { cur[replay.inputs[ii][1]] = replay.inputs[ii][2]; ii++; }
    }
    step(S, replay ? cur : undefined); camStep(cam, S, S.dt, 1200, 700); steps++;
    h.num(S.T); h.num(S.rng.a | 0);
    for (const f of S.fighters) { for (const k of ['x', 'y', 'vx', 'vy', 'hp', 'ki', 'power', 'tier', 'stance']) h.num(f[k]); h.str(f.state); }
    for (const l of S.out.feed) { h.num(l.t); h.str(l.tag); h.str(l.sub); }
    S.out.feed.length = 0;
    if (steps % CHECK_EVERY === 0) checkpoints.push(full(S, cam));
  }
  return { arm, seed, ticks: steps, light: h.hex(), checkpoints, final: full(S, cam) };
}

// A scripted human (P1, and P2 when both) as a replay: moves, dashes, charges, switches stance and presses attacks.
function scriptedReplay(seed, ticks, both, toggleAt) {
  const r = createRng(seed ^ 0x51ed), held = [{ mx: 0, my: 0, dash: false, charge: false }, { mx: 0, my: 0, dash: false, charge: false }];
  const rp = { seed, ai: { p1: false, p2: !both }, ticks, inputs: [], toggles: toggleAt.map(t => [t, 1]) };
  const last = [null, null];
  for (let t = 0; t < ticks; t++) for (let k = 0; k < (both ? 2 : 1); k++) {
    const hk = held[k];
    if (next(r) < 0.05) hk.mx = [-1, 0, 1][Math.floor(next(r) * 3)];
    if (next(r) < 0.05) hk.my = [-1, 0, 1][Math.floor(next(r) * 3)];
    if (next(r) < 0.02) hk.dash = !hk.dash;
    if (next(r) < 0.01) hk.charge = !hk.charge;
    const i = { ...hk, light: next(r) < 0.03, heavy: next(r) < 0.015, sig: next(r) < 0.008, stance: next(r) < 0.004 ? Math.floor(next(r) * 4) : -1 };
    if (!last[k] || INTENT.some(q => last[k][q] !== i[q])) { rp.inputs.push([t, k, i]); last[k] = i; }
  }
  return rp;
}
export const REPLAYS = [scriptedReplay(11, 3000, false, [1500, 2100]), scriptedReplay(12, 2400, true, [])];

export function build() {
  const g = { format: 'meridian-golden-gd', v: 1, note: 'Written by node sim/core/tools/golden.js (JS core, math det). Checked by sim/core/tools/parity.gd.' };
  const C = D.CONSTANTS;
  g.constants = [C.PIO2_1, C.PIO2_1T, C.INVPIO2, C.LN2_HI, C.LN2_LO, C.INVLN2, C.SQRT2, C.SQRT_HALF, ...C.SIN_C, ...C.COS_C, ...C.EXP_C, ...C.LOG_C].map(bits);

  g.rng = {};
  for (const seed of [0, 1, 7, 4242, 2147483647, 2147483648, 4294967295, 12345]) {
    const r = createRng(seed), h = new Hasher();
    for (let i = 0; i < 5000; i++) h.num(next(r));
    h.num(r.a | 0);
    g.rng[seed] = h.hex();
  }

  let h = new Hasher();
  for (let i = 0; i < 8001; i++) h.num(wrap(-40000 + i * 10.0037));
  for (let i = 0; i < 2000; i++) { const a = i * 4.8 + 0.3, b = 9599.7 - i * 3.3; h.num(sdx(a, b)); h.num(sdx(b, a)); }
  g.wrap = h.hex();

  h = new Hasher();
  for (let i = 0; i < 102190; i++) { const x = -700 + i * 0.0137; h.num(D.sin(x)); h.num(D.cos(x)); }
  g.sincos = h.hex();
  h = new Hasher();
  const bases = [0.55, 0.05, 0.1, 0.001, 0.0008, 0.03, 0.02, 0.98, 0.5, 1.5, 7.25];
  const exps = [DT, DT * 0.35, DT * 0.1, DT * 0.35 * 0.1, 1, 0.35, 0.1, 0.035, 2, 0.5, -1.5, 3.7];
  for (const b of bases) for (const e of exps) h.num(D.pow(b, e));
  for (let i = 0; i < 4616; i++) h.num(D.exp(-30 + i * 0.013));
  for (let i = 0; i < 3000; i++) h.num(D.log(0.0001 + i * 0.37));
  for (let i = 0; i < 2000; i++) h.num(D.hypot(i * 1.7 - 1500, 900 - i * 0.9));
  g.powexplog = h.hex();

  g.tick0 = {};
  for (const seed of [1, 2, 3, 42, 1000, 4294967295]) {
    const S = createSim({ math: 'det' }); newMatch(S, seed);
    g.tick0[seed] = stateHash(S);
  }
  const S = createSim({ math: 'det' }); newMatch(S, 1);
  g.tick0Values = collect(portSrc(S), 'gameplay').map(tag);

  g.literals = gdLiterals();
  g.checkEvery = CHECK_EVERY;
  g.matches = MATCHES.map(([arm, seed]) => goldenRun(arm, seed));
  g.replays = REPLAYS.map(rp => ({ replay: rp, run: goldenRun('default', rp.seed, rp) }));
  return g;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const g = build(), text = JSON.stringify(g, null, 1) + '\n';
  if (process.argv.includes('--check')) {
    const cur = fs.existsSync(GOLDEN) ? fs.readFileSync(GOLDEN, 'utf8') : '';
    if (cur !== text) { console.log('FAIL  golden-gd.json is stale: the JS core or a .gd literal changed. Run: node sim/core/tools/golden.js'); process.exit(1); }
    console.log('ok    golden-gd.json is current');
  } else {
    fs.writeFileSync(GOLDEN, text);
    console.log(`wrote ${path.relative(process.cwd(), GOLDEN)}: ${g.constants.length} constants, ${Object.keys(g.rng).length} rng streams, ${Object.keys(g.tick0).length} tick-0 states, ${g.literals.length} .gd float literals, ${g.matches.length} matches (${g.matches.reduce((a, m) => a + m.ticks, 0)} ticks), ${g.replays.length} human-input replays`);
  }
}
